import { StyleSheet } from 'react-native';
import { shadows } from '../../utils/shadows';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F4F7FC",
    paddingHorizontal: 0,
  },
  // Parent-like header styles
  parentLikeHeaderContainer: {
    paddingTop: 40,
    paddingBottom: 8,
    paddingHorizontal: 2,
  },
  parentLikeHeaderGradient: {
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  logoImage: {
    width: 60,
    height: 80,
  },
  headerBadge: {
    backgroundColor: '#e3f2fd',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
    alignSelf: 'flex-start',
  },
  headerBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#2196f3',
  },
  headerActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    flexShrink: 0,
    maxWidth: 160,
    justifyContent: 'flex-end',
  },
  headerButton: {
    padding: 6,
    marginLeft: 4,
    marginBottom: 4,
    minWidth: 36,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    ...shadows.md,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  profileImageContainer: {
    position: "relative",
    marginRight: 16,
  },
  profileImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 2,
    borderColor: "#E5E7EB",
  },
  verifiedBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#10B981",
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 4,
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  ratingText: {
    fontSize: 14,
    color: "#6B7280",
    marginLeft: 4,
  },
  profileDetail: {
    fontSize: 14,
    color: "#6B7280",
  },
  profileAge: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 2,
  },
  profileContact: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 2,
  },
  editProfileButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F3F4F6",
    justifyContent: "center",
    alignItems: "center",
  },
  tabs: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    marginTop: 16,
    marginHorizontal: 16,
    borderRadius: 12,
    padding: 4,
    ...shadows.sm,
  },
  tab: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 8,
  },
  activeTab: {
    backgroundColor: "#EFF6FF",
  },
  tabText: {
    fontSize: 12,
    fontWeight: "500",
    color: "#6B7280",
    marginLeft: 6,
  },
  activeTabText: {
    color: "#2563EB",
    fontWeight: "600",
  },
  // Parent-style horizontal top nav
  navContainer: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  navScroll: {
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  navTab: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    minWidth: 100,
  },
  navTabActive: {
    backgroundColor: '#bed6fc',
    borderColor: '#bed6fc',
  },
  navTabText: {
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '500',
    color: '#6b7280',
  },
  navTabTextActive: {
    color: '#3b83f5',
    fontWeight: '600',
  },
  // Legacy styles for compatibility
  navItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  activeNavItem: {
    backgroundColor: '#bed6fc',
    borderColor: '#bed6fc',
  },
  navText: {
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '500',
    color: '#6b7280',
  },
  activeNavText: {
    color: '#3b83f5',
  },
  content: {
    flex: 1,
    paddingTop: 16,
  },
  searchBar: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    elevation: 0,
    height: 48,
  },
  searchInput: {
    fontSize: 14,
    color: "#111827",
    paddingBottom: 0,
    marginBottom: 0,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  // New quick stats and actions grids
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    marginBottom: 16,
    gap: 12,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    marginBottom: 24,
    gap: 12,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    marginBottom: 24,
    gap: 12,
  },
  quickTile: {
    width: '48%',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    ...shadows.sm,
  },
  quickActionTile: {
    width: '48%',
    borderRadius: 16,
    overflow: 'hidden',
    ...shadows.md,
  },
  quickActionGradient: {
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    minHeight: 100,
    justifyContent: 'center',
  },
  quickIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  quickActionIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  quickValue: {
    fontSize: 24,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 4,
    lineHeight: 28,
  },
  quickLabel: {
    fontSize: 13,
    fontWeight: '500',
    color: '#6B7280',
    textAlign: 'center',
  },
  quickActionLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    lineHeight: 18,
  },
  statCard: {
    width: '31%',
    borderRadius: 12,
    padding: 16,
    ...shadows.xs,
  },
  statIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#6B7280',
  },
  section: {
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  promotionCard: {
    borderRadius: 16,
    borderWidth: 2,
    marginBottom: 8,
    overflow: 'hidden',
    ...shadows.md,
  },
  promotionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  promotionIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  promotionContent: {
    flex: 1,
  },
  promotionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
    lineHeight: 20,
  },
  promotionDescription: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 18,
  },
  promotionButton: {
    borderRadius: 12,
    marginTop: 4,
  },
  jobsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    lineHeight: 24,
  },
  seeAllText: {
    color: '#3B82F6',
    fontSize: 14,
    fontWeight: '500',
  },
  horizontalScroll: {
    paddingVertical: 8,
    paddingLeft: 0,
    paddingRight: 0,
  },
  jobCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    marginVertical: 4,
  },
  jobCardHorizontal: {
    width: 300,
    marginRight: 16,
    marginBottom: 4,
    minHeight: 280,
    padding: 0,
  },
  jobCardTablet: {
    width: '31%',
  },
  jobHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  jobTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 8,
    lineHeight: 24,
  },
  jobMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginBottom: 4,
  },
  jobMetaText: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 4,
    marginRight: 12,
  },
  jobMetaIcon: {
    marginLeft: 12,
    marginRight: 4,
  },
  urgentBadge: {
    backgroundColor: '#FEE2E2',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
    alignSelf: 'flex-start',
  },
  urgentBadgeText: {
    color: '#DC2626',
    fontSize: 10,
    fontWeight: '600',
  },
  jobDetails: {
    marginBottom: 16,
    gap: 8,
  },
  jobDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  jobDetailText: {
    fontSize: 13,
    color: '#4B5563',
    marginLeft: 8,
  },
  requirementsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
    gap: 6,
  },
  requirementTag: {
    backgroundColor: '#EFF6FF',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#DBEAFE',
  },
  requirementText: {
    fontSize: 12,
    color: '#2563EB',
    fontWeight: '500',
  },
  moreRequirementsText: {
    fontSize: 12,
    color: '#9CA3AF',
    alignSelf: 'center',
  },
  jobFooter: {
    flexDirection: 'column',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    gap: 12,
  },
  postedDate: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  jobActionButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    height: 40,
  },
  secondaryButtonText: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '500',
  },
  primaryButton: {
    flex: 1,
    backgroundColor: '#2563EB',
    borderRadius: 8,
    height: 40,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '500',
  },
  applicationCard: {
    marginBottom: 12,
    borderRadius: 12,
    ...shadows.sm,
  },
  applicationContent: {
    padding: 16,
  },
  applicationHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  applicationJobTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 2,
  },
  applicationFamily: {
    fontSize: 14,
    color: '#6B7280',
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
  },
  statusText: {
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 4,
  },
  statusIcon: {
    marginRight: 4,
  },
  applicationDetails: {
    marginBottom: 12,
  },
  applicationDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  applicationDetailText: {
    fontSize: 13,
    color: '#4B5563',
    marginLeft: 8,
  },
  applicationActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  applicationButton: {
    minWidth: 100,
  },
  applicationButtonText: {
    fontSize: 13,
    fontWeight: '500',
  },
  bookingCard: {
    marginBottom: 16,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    ...shadows.md,
  },
  bookingContent: {
    padding: 20,
  },
  bookingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  bookingTitleSection: {
    flex: 1,
    marginRight: 12,
  },
  bookingFamily: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
    lineHeight: 22,
  },
  bookingDate: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  bookingDetails: {
    marginBottom: 20,
  },
  bookingDetailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  bookingDetailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  bookingDetailText: {
    fontSize: 14,
    color: '#4B5563',
    marginLeft: 8,
    fontWeight: '500',
  },
  bookingLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginLeft: 8,
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
  },
  bookingLocationText: {
    fontSize: 14,
    color: '#2563EB',
    fontWeight: '500',
    flex: 1,
  },
  locationIcon: {
    marginLeft: 6,
  },
  bookingActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    gap: 12,
  },
  bookingSecondaryButton: {
    flex: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    minHeight: 44,
  },
  bookingSecondaryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  bookingPrimaryButton: {
    flex: 1,
    backgroundColor: '#2563EB',
    borderRadius: 12,
    minHeight: 44,
  },
  bookingPrimaryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  bookingConfirmButton: {
    flex: 1,
    backgroundColor: '#059669',
    borderRadius: 12,
    minHeight: 44,
  },
  bookingConfirmButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  profileSection: {
    marginBottom: 16,
    borderRadius: 12,
    ...shadows.sm,
  },
  profileSectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  profileSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  profileSectionContent: {
    padding: 16,
  },
  profileSectionText: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
  },
  // Settings components styles
  settingsContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginHorizontal: 16,
    marginBottom: 16,
    ...shadows.sm,
  },
  settingsHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  settingsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  settingsContent: {
    padding: 16,
  },
  settingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F9FAFB',
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
    flex: 1,
  },
  settingDesc: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 2,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
  },
  textInputDisabled: {
    backgroundColor: '#F9FAFB',
    opacity: 0.6,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
  },
  saveButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 16,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  sectionDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: 16,
  },
  sectionSubtitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 12,
  },
  skillsSection: {
    marginBottom: 16,
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  skillTag: {
    backgroundColor: '#EFF6FF',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  skillText: {
    color: '#2563EB',
    fontSize: 13,
    fontWeight: '500',
  },
  certificationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  certificationIcon: {
    marginRight: 12,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyStateText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
    marginTop: 16,
    marginBottom: 4,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  filters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
  },
  filterChip: {
    marginRight: 8,
    marginBottom: 8,
    backgroundColor: '#F3F4F6',
    borderRadius: 16,
  },
  filterChipActive: {
    backgroundColor: '#EFF6FF',
  },
  filterChipText: {
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '500',
  },
  filterChipTextActive: {
    color: '#2563EB',
  },
  bookingFilters: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  bookingFilterChip: {
    marginRight: 8,
    backgroundColor: '#F3F4F6',
    borderRadius: 20,
  },
  bookingFilterChipActive: {
    backgroundColor: '#EFF6FF',
  },
  bookingFilterChipText: {
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '500',
  },

  logoutButton: {
    margin: 16,
    backgroundColor: '#2563EB',
    borderRadius: 8,
  },
  logoutButtonText: {
    color: '#FFFFFF',
    fontWeight: '500',
  },
  // Badge shown when caregiver already applied to a job
  appliedBadge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#E8F5E9',
    borderColor: '#C8E6C9',
    borderWidth: 1,
    flexShrink: 1,
  },
  appliedBadgeContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  appliedBadgeText: {
    color: '#2E7D32',
    fontWeight: '600',
  },
  // Modal overlay
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Loading states
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
  },
  loadingText: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 12,
    fontWeight: '500',
  },
  // Application Modal Styles
  applicationModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    margin: 20,
    maxHeight: '85%',
    width: '90%',
    alignSelf: 'center',
    ...shadows.lg,
  },
  applicationModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  applicationModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  modalCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  jobSummary: {
    padding: 20,
    backgroundColor: '#F8FAFC',
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  jobSummaryTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  jobSummaryFamily: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
  },
  jobSummaryRate: {
    fontSize: 16,
    fontWeight: '600',
    color: '#059669',
  },
  applicationFormContainer: {
    padding: 20,
  },
  applicationInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
    color: '#111827',
    width: '100%',
    flex: 0,
  },
  applicationTextArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  applicationModalActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    gap: 12,
  },
  cancelButton: {
    flex: 1,
    borderColor: '#D1D5DB',
  },
  submitButton: {
    flex: 1,
    backgroundColor: '#2563EB',
  },
  // Edit Profile Modal Styles
  editProfileModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    margin: 20,
    maxWidth: 400,
    width: '90%',
    alignSelf: 'center',
    ...shadows.lg,
  },
  editProfileTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 20,
    textAlign: 'center',
  },
  editProfileInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
    color: '#111827',
    marginBottom: 16,
  },
  editProfileSaveButton: {
    backgroundColor: '#2563EB',
    borderRadius: 8,
    marginBottom: 12,
  },
  editProfileSaveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  // Profile Card Styles
  profileCard: {
    marginBottom: 24,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    ...shadows.md,
  },
  profileImagePlaceholder: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  profileEmail: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
  },
  profileStats: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileRate: {
    fontSize: 16,
    fontWeight: '700',
    color: '#059669',
    marginRight: 16,
  },
  profileExperience: {
    fontSize: 14,
    color: '#6B7280',
  },
  profileBio: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
  },
  skillsPreview: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  skillsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 8,
  },
  skillChip: {
    backgroundColor: '#EFF6FF',
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 4,
  },
  skillChipText: {
    color: '#2563EB',
    fontSize: 12,
    fontWeight: '500',
  },
  moreSkillsText: {
    fontSize: 12,
    color: '#9CA3AF',
    alignSelf: 'center',
  },
  ageCarePreview: {
    marginTop: 12,
  },
  ageCareTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  ageCareText: {
    fontSize: 14,
    color: '#4B5563',
  },
  editProfileSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginBottom: 20,
  },
  profileLocation: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 4,
  },
  certificationsPreview: {
    marginTop: 12,
  },
  certificationsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 8,
  },
  certificationsContainer: {
    marginBottom: 8,
  },
  certificationText: {
    fontSize: 14,
    color: '#4B5563',
    marginBottom: 4,
  },
  moreCertificationsText: {
    fontSize: 12,
    color: '#9CA3AF',
  },
});
